### ISSUE TITLE
Actually do something!

### ISSUE THREAD

**Issue by AmaanC** [ryankinal/gamora#1]
Don't let it fall into the "never got around to it" blackhole!

**Comment by ryankinal** [comment]
Best. Issue. Ever.

Seriously, though, since I've released something for Certified Random, I'll probably get moving on this.

**Comment by AmaanC** [comment]
Yaaaaay!

**Comment by AmaanC** [comment]
Pssst.

**Comment by ryankinal** [comment]
Haha, I was wondering when you'd notice all t3h c0d3z
